-- V001__create_tables.sql

-- Таблица product
CREATE TABLE public.product (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255)
);

-- Таблица product_info
CREATE TABLE public.product_info (
    product_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION
);

-- Таблица orders
CREATE TABLE public.orders (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(255)
);

-- Таблица orders_date
CREATE TABLE public.orders_date (
    order_id BIGINT NOT NULL,
    status VARCHAR(255),
    date_created DATE DEFAULT CURRENT_DATE
);

-- Таблица order_product
CREATE TABLE public.order_product (
    quantity BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);