---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongodb_uri: {{ printf "mongodb://%s:%s@%s:%v/%s?authSource=%s" (.Values.global.mongodb.username | urlquery | replace "+" "%20") (.Values.global.mongodb.password | urlquery | replace "+" "%20") .Values.global.mongodb.host .Values.global.mongodb.port .Values.global.mongodb.database .Values.global.mongodb.database | quote }}
